In [1]:
import torch 
print(torch.__version__)

2.9.1+cpu


In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


creating torch


In [5]:
# using empty
a = torch.empty(2,3)

In [6]:
# checking type
type(a)

torch.Tensor

In [ ]:
# using zeros
# for making 2 by 3 matrix of 0
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones 
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.4247, 0.8519, 0.9680],
        [0.7342, 0.8135, 0.6924]])

In [14]:
# mannual seed used for generating random numbers and return generator object
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [17]:
# using tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways 

# arrange
#  0 to 10 me banega aur 2-2 ki gap me 
print("using arrange -> ", torch.arange(0,10,2))

# using linespace 
# 0 to 10 me 10 values banega equally spaced
print("using linespace -> ", torch.linspace(0,10,10))

# using eye
# ek 5,5 ki identity matrix banega
print("using eye -> ", torch.eye(5))

# using full 
# 3 by 3 matrix banega jisme sabhi values 5 hongi
print("using full -> " , torch.full((3,3),5))

using arrange ->  tensor([0, 2, 4, 6, 8])
using linespace ->  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensors Shapes

In [23]:
z= torch.tensor([[1,2,3],[4,5,6]])
z


tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
z.shape

torch.Size([2, 3])

In [25]:
torch.empty_like(z)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.zeros_like(z)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(z)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
torch.rand_like(z, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensors Datatypes

In [31]:
# find data type
z.dtype

torch.int64

In [32]:
# assign data types
torch.tensor([1.0,2.0,3.0], dtype=torch.float64)


tensor([1., 2., 3.], dtype=torch.float64)

In [33]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [34]:
#  using to
z.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical Operation 

Scalar Operation

In [35]:
x= torch.rand(2,2)

In [36]:

x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [37]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

In [38]:
# ELEMENT WISE OPERATION

a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [39]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [40]:
c = torch.tensor([1, -2, 3, -4])

In [41]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [42]:
# negative 
torch.neg(c)

tensor([-1,  2, -3,  4])

In [44]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [47]:

d = torch.round(d)
d

tensor([2., 2., 4., 4.])

In [48]:
# ceil
torch.ceil(d)

tensor([2., 2., 4., 4.])

In [49]:
# floor
torch.floor(d)

tensor([2., 2., 4., 4.])

In [50]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2., 2., 3., 3.])

In [57]:
# REDUCE OPERATION
e= torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [58]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15., 13.])

In [59]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [60]:
# median
torch.median(e)

tensor(4.)

In [61]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [63]:
# product
torch.prod(e)

tensor(0.)

In [64]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [65]:
# variance
torch.var(e)

tensor(9.8667)

In [66]:
# argmax
torch.argmax(e)

tensor(3)

In [67]:
# argmin
torch.argmin(e)

tensor(5)

MATRIX MULTIPLICATION

In [68]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g) 

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [69]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [70]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose 
# here f means first row 
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [72]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[2., 6., 7.],
        [7., 8., 3.],
        [6., 1., 5.]])

In [73]:
# determinant
torch.det(h)

tensor(-315.)

In [74]:
# inverse
torch.inverse(h)

tensor([[-0.1175,  0.0730,  0.1206],
        [ 0.0540,  0.1016, -0.1365],
        [ 0.1302, -0.1079,  0.0825]])

Comparison operations 

In [75]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[5, 0, 4],
        [3, 8, 8]])
tensor([[3, 3, 5],
        [0, 6, 4]])


In [76]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

Special functions

In [77]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 8., 4.],
        [7., 2., 3.]])

In [78]:
# log
torch.log(k)

tensor([[  -inf, 2.0794, 1.3863],
        [1.9459, 0.6931, 1.0986]])

In [79]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 2.9810e+03, 5.4598e+01],
        [1.0966e+03, 7.3891e+00, 2.0086e+01]])

In [80]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.8284, 2.0000],
        [2.6458, 1.4142, 1.7321]])

In [81]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9997, 0.9820],
        [0.9991, 0.8808, 0.9526]])

In [82]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.9753e-01, 7.3106e-01],
        [9.9909e-01, 2.4726e-03, 2.6894e-01]])

In [83]:
# relu
torch.relu(k)

tensor([[0., 8., 4.],
        [7., 2., 3.]])

Inplace Operations


In [84]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])
tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [85]:
m.add_(n)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [86]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [87]:
n

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [88]:
torch.relu(m)

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [89]:
m.relu_()

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

In [90]:
m

tensor([[0.7776, 0.3072, 1.8746],
        [1.0939, 0.1762, 1.3909]])

Copying a Tensor

In [91]:
a = torch.rand(2,3)
a

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [92]:
b=a

In [93]:
b

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [94]:
a[0][0] = 0

In [95]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [96]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [97]:
id(a)

2945251716512

In [98]:
id(b)

2945251716512

In [99]:
b=a.clone()

In [100]:
a

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [101]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [102]:
a[0][0] = 9

In [103]:
a

tensor([[9.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [104]:
b

tensor([[0.0000, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])

In [105]:
id(a)

2945251716512

In [106]:
id(b)

2945251716032