In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [11]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [12]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [13]:
#  doing train test split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [14]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [15]:
X_train

array([[-0.72567562, -0.07038362, -0.73047326, ..., -0.70765116,
         0.2444398 , -0.04898192],
       [ 2.08286058, -0.98206509,  2.05932984, ...,  1.28669765,
        -0.26695942,  0.16133299],
       [ 1.5727387 , -0.27632182,  1.61861579, ...,  1.7179165 ,
         1.26388478,  0.46799635],
       ...,
       [ 0.54962908,  0.90145957,  0.45446546, ..., -0.19954952,
         0.09856527,  0.0435126 ],
       [ 0.04237306,  0.64924312,  0.19336318, ...,  1.00893747,
        -0.07581348,  1.62252611],
       [ 1.5297509 , -0.12128969,  1.51051612, ...,  1.4309488 ,
         0.63176182,  0.35017596]])

In [16]:
y_train

420    B
372    M
162    M
236    M
461    M
      ..
211    B
50     B
10     M
62     M
487    M
Name: diagnosis, Length: 455, dtype: object

In [17]:
# label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [18]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,

In [19]:
#  NUMPY ARRAYS TO PYTORCH TENSORS
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))


In [21]:
X_train_tensor.shape

torch.Size([455, 30])

In [22]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
from torch.utils.data import Dataset, DataLoader

class customDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features 
        self.labels = labels
        
        #  WE WANT FEATURES LENGTH
    def __len__(self):
        return len(self.features)
    
    # IN GET ITEM WE WANT FEATURES ID
    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]    

In [26]:
train_dataset = customDataset(X_train_tensor, y_train_tensor)
test_dataset = customDataset(X_test_tensor, y_test_tensor)

In [27]:
train_dataset[10]

(tensor([ 1.5326, -0.0033,  1.4440,  1.4819,  0.5494,  0.2923,  0.6339,  0.9980,
         -0.1196, -0.8817,  0.6774, -1.1057,  0.4691,  0.6477, -0.7904, -0.4101,
         -0.1508,  0.1595, -0.8446, -0.4563,  1.9842, -0.1958,  1.7127,  1.9376,
          0.8078,  0.4075,  0.7621,  1.3373,  0.8212,  0.3177]),
 tensor(1.))

In [29]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [ ]:
# NOW WE ARE DEFINING THE MODEL

import torch.nn as nn

class MySimpleNN(nn.Module):
    
    def __init__(self, num_features):
        
        super().__init__()
        # here one is output
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out    

In [31]:
learning_rate = 0.1
epochs=25

In [32]:
# creating the model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer 
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

In [33]:
# TRAINING PIPLEINE 
for epoch in range(epochs):
    
    for batch_features, batch_labels in train_loader:
        
        # forward pass
        y_pred = model(batch_features)
        
        # loss function
        loss = loss_function(y_pred, batch_labels.view(-1,1))
        
        # clear gradients
        optimizer.zero_grad()
        
        # backward pass
        loss.backward()
        
        # parameters update
        optimizer.step()
        
        # print loss in each epoch
        print(f'epoch: {epoch+1}, loss: {loss.item()}')

epoch: 1, loss: 0.7895793318748474
epoch: 1, loss: 0.6257895231246948
epoch: 1, loss: 0.5880180597305298
epoch: 1, loss: 0.4570196568965912
epoch: 1, loss: 0.37624552845954895
epoch: 1, loss: 0.30937373638153076
epoch: 1, loss: 0.29521289467811584
epoch: 1, loss: 0.3432449698448181
epoch: 1, loss: 0.2690885066986084
epoch: 1, loss: 0.2311791032552719
epoch: 1, loss: 0.3001691401004791
epoch: 1, loss: 0.22267648577690125
epoch: 1, loss: 0.2928931713104248
epoch: 1, loss: 0.28683745861053467
epoch: 1, loss: 0.1810200959444046
epoch: 2, loss: 0.2750813961029053
epoch: 2, loss: 0.19377589225769043
epoch: 2, loss: 0.16952651739120483
epoch: 2, loss: 0.22596776485443115
epoch: 2, loss: 0.15691892802715302
epoch: 2, loss: 0.15486253798007965
epoch: 2, loss: 0.13500897586345673
epoch: 2, loss: 0.1990312933921814
epoch: 2, loss: 0.2181505262851715
epoch: 2, loss: 0.20481184124946594
epoch: 2, loss: 0.12868544459342957
epoch: 2, loss: 0.2142258733510971
epoch: 2, loss: 0.15148067474365234
epoch:

In [34]:
# evaluation

model.eval()

accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9509
